config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles do
    get 'export_file'
    get 'update_status'
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base	
	has_many :comments
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	validates :title, presence: true, length: { minimum: 5 }		

  def create_file(article)
    file = File.open("#{Rails.root}/export_file/#{article.title}.txt", "w") do |f|
      f.write "The content of article is #{article.text}"
      puts "Write file OKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
      f.close
      puts "File is close OKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK"
    end
  end  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_id, only: [:show, :edit, :update, :destroy]


  def index
    @articles = Article.all.order(:id).paginate(page: params[:page], per_page: 5)
  end

  def show

  end

  def new
    console
    @article = Article.new
  end

  def edit

  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    render json: {status: "delete success"}
  end

  def export_file
    @article = Article.find(params[:article_id])
    @article.delay(run_at: 30.seconds.from_now).create_file @article
    redirect_to articles_path

    puts "redirect successssssssssssssssssssssssssssssssssss"
  end

  def update_status
    @article = Article.find(params[:article_id])
    if @article.image_upload_status == true
      render json: {status: "fail"}
      puts "update NOTTTTTTTTTT okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
    else
      @article.update_column(:image_upload_status, true)
      render json: {status: "ok"}
      puts "update okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :avatar, :image_upload_status)
  end

  def find_id
    @article = Article.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_article_id 

  def index		
	@comments = @article.comments.all
  end
  def create    
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  private
  	def find_article_id
  	  @article = Article.find(params[:article_id])
  	end

    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>	
    <div id="error_explanation">
      <h2>
      	<%= pluralize(@article.errors.count, "errors") %> prohibited this article from being saved:
      </h2>
      <ul>
      	<% @article.errors.full_messages.each do |msg| %>
      	  <li><%= msg %></li>
      	<% end %>
      </ul>
    	
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>  

  <p>
    <%= f.file_field :avatar %>        
  </p>

  <p>    
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="icon-ok icon-white"></i> Submit
    <% end %>
  </p>

  <p>
    <%= link_to 'Back', articles_path %>
  </p>  

<% end %>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
<h1>Edit article</h1>
 
<%= render 'form' %>


</div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h2>Listing articles</h2>
  <p><%= link_to 'New article', new_article_path %></p>
  <p id="msg"></p>
  <table class="table table-bordered">
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td>ID: <%= article.id %></td>
          <td>Title: <%= article.title %></td>
          <td>Text: <%= article.text %></td>
          <td>Status: <%= article.image_upload_status %></td>
          <td id="<%= article.id %>">Action: <%= link_to 'Show', article_path(article) %>
            <%= link_to 'Edit', edit_article_path(article) %>
            <%= link_to "Export", article_export_file_path(article) %>
            <button class="delete">Delete</button>
            <button class="update">UpdateStt</button> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <button id="ext-js_button"></button>
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
<h2>New article</h2>

<%= render 'form' %>

</div>
</div>

app/views/articles/show.html.erb
<div class="row">
<div class="container">

<table class="table table-bordered">
<h2>Article details</h2>
<tbody>
 <tr>
  <th class="col-xs-1"> <strong>ID:</strong> </th>
  <td> <%= @article.id %> </td>
 </tr>
 <tr>
  <th> <strong>Title:</strong> </th>
  <td> <%= @article.title %> </td>
 </tr>
 <tr>
  <th> <strong>Text:</strong> </th>
  <td> <%= @article.text %> </td>
 </tr>
 <tr>
  <th> <strong>Avatar:</strong> </th>
  <td> <%= image_tag @article.avatar.url, class: "img-thumbnail", size: "80x80" %> </td>
 </tr>
</tbody> 
</table>

<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
      <i class="icon-ok icon-white"></i> Comment
    <% end %>
  </p>    
<% end %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
  
</div>  
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/index.html.erb
<h1>Listing comment</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.id %></td>    
      <td><%= comment.commenter %></td>
      <td><%= comment.body %></td>      
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>